version: "3.7"
services:
    db:
        image: mysql:8.0
        container_name: livewallet-db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            MYSQL_ROOT_PASSWORD:
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - livewallet
    redis:
        image: redis:6.2-alpine
        container_name: livewallet-redis
        restart: unless-stopped
        ports:
            - 6379:6379
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        volumes:
            - ./cache:/data
        networks:
            - livewallet
    app:
        build:
            args:
                user: sbenard
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: livewallet
        container_name: livewallet-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - livewallet
    nginx:
        image: nginx:alpine
        container_name: livewallet-nginx
        restart: unless-stopped
        depends_on:
            - db
            - redis
            - app
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - livewallet
networks:
    livewallet:
        driver: bridge
